[package]
name = "minio-rs"
version = "0.1.0"
authors = ["Aditya Manthramurthy <aditya.mmy@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.12.28"
ring = "0.14.6"
time = "0.1.42"
http = "0.1.17"
hyper-tls = "0.3.2"
futures = "0.1.27"
bytes = "0.4.12"
